stages:
- validate
- plan
- apply
- destroy

variables:
  TOFU_DIR: "tofu"

default:
  image: registry.gitlab.com/gkermo/ecostream/opentofu/gitlab-opentofu:1.1.0-opentofu1.9.0-alpine-amd64
  before_script:
  - |
    cd $TOFU_DIR
    tofu --version
    tofu init -backend-config="address=https://gitlab.com/api/v4/projects/68895536/terraform/state/${ENV_NAME}" \
      -backend-config="lock_address=https://gitlab.com/api/v4/projects/68895536/terraform/state/${ENV_NAME}/lock" \
      -backend-config="unlock_address=https://gitlab.com/api/v4/projects/68895536/terraform/state/${ENV_NAME}/lock" \
      -backend-config="username=${GITLAB_USERNAME}" \
      -backend-config="password=${GITLAB_TOKEN}"

validate:
  stage: validate
  script:
  - tofu validate

plan:
  stage: plan
  script:
  - tofu plan -input=false -var-file="tofu.tfvars"
  artifacts:
    paths:
    - $TOFU_DIR/planfile
    when: always

apply:
  stage: apply
  script:
  - tofu apply -auto-approve -input=false -var-file="tofu.tfvars"
  when: manual

destroy:
  stage: destroy
  script:
  - tofu destroy -auto-approve -input=false -var-file="tofu.tfvars"
  when: manual
