stages:
- validate
- plan
- apply
- destroy

variables:
  TOFU_DIR: "tofu"

default:
  image: $CI_TEMPLATE_REGISTRY_HOST/components/opentofu/opentofu/gitlab-opentofu:1.9.0
  before_script:
  - cd $TOFU_DIR
  - tofu --version
  - tofu init

validate:
  stage: validate
  script:
  - tofu validate

plan:
  stage: plan
  script:
  - tofu plan -input=false -var-file="tofu.tfvars"
  artifacts:
    paths:
    - $TOFU_DIR/planfile
    when: always

apply:
  stage: apply
  script:
  - tofu apply -auto-approve -input=false -var-file="tofu.tfvars"
  when: manual

destroy:
  stage: destroy
  script:
  - tofu destroy -auto-approve -input=false -var-file="tofu.tfvars"
  when: manual
