- name: Setup EKS environment
  hosts: localhost
  gather_facts: false
  roles:
    - role: kubeconfig
    - role: eks_access
    - role: ecostream_namespace
    - role: argocd
    - role: prometheus_grafana
    - role: post_deploy
