- name: Create namespace "{{ ecostream_namespace }}" on EKS cluster
  kubernetes.core.k8s:
    state: present
    # kubeconfig: "{{ kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ ecostream_namespace }}"

# TODO: create a Secret with GitLab access